apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: template-app-tls
spec:
  secretName: template-app
  issuerRef:
    name: issuer-config
    kind: ClusterIssuer
  commonName: template.app
  dnsNames:
    - template.app
    - www.template.app
