apiVersion: cert-manager.io/v1

kind: Certificate
metadata:
  name: e-voting-app-tls
spec:
  secretName: e-voting-app
  issuerRef:
    name: issuer-config
    kind: ClusterIssuer
  commonName: e-voting.app
  dnsNames:
    - e-voting.app
    - www.e-voting.app
