FROM python:3.9.17

RUN mkdir /srv/be-service-voting
WORKDIR /srv/be-service-voting

COPY ./requirements.txt .
RUN pip install -r ./requirements.txt

RUN pip install uwsgi

# Copy the rest of your application's necessary files
COPY . .

EXPOSE 9069

ENV NAME World

CMD ["uwsgi", "--ini", "uwsgi.ini"]