FROM python:3.9.17

RUN mkdir /srv/be-service-voting
WORKDIR /srv/be-service-voting

COPY ./requirements.txt .
RUN pip install -r ./requirements.txt

EXPOSE 5000

COPY . .

RUN echo "Running Main Dockerfile"
CMD ["python", "app.py"]
